# Generated by Django 3.1.14 on 2024-02-29 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 15, 55, 7, 198007, tzinfo=utc)),
        ),
    ]
